### ISSUE TITLE
s3 command won't generate any bullet tokens or web service tokens

### ISSUE THREAD

**Issue by InkxtheSquid** [Jetsurf/nso-api#2]
the s3 command is not generating any tokens, therefore I'm not getting any results from the command
![image](https://github.com/Jetsurf/nso-api/assets/17834792/c391180c-c275-4dc9-9dbd-3b1475019d8b)

**Comment by Jetsurf** [comment]
Is the error repeated if you attempt to run it again? Not sure why iMink (the f_provider here) would be responding like that.

I also attempted to run `nso-cli.py s3 get-splatfest-list` on a fresh install and it worked for me. Could you also provide what you're calling nso-cli.py with?

**Comment by Jetsurf** [comment]
Glad it was that simple! Just as a small heads up, the iMink API occasionally has a hiccup like that, The typical "fix" is to just run it again.
