### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' using nso-cli.py --login

### ISSUE THREAD

**Issue by Dyr-Fenrir** [Jetsurf/nso-api#3]
Greetings,

I always get the following errors when attempting to login using nso-cli.py --login:
```
Traceback (most recent call last):
  File "G:\Program Files\Python\nso-api\nso-api-main\nso-cli.py", line 281, in <module>
    if nso.complete_login_challenge(input):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Program Files\Python\nso-api\nso-api-main\nso_api\nso_api.py", line 507, in complete_login_challenge
    if not result.get('session_token'):
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

I paste the URL in the browser and copy the link of the "Select this account" button and then paste it in the console window, then press ENTER.

I am using Python version 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) on a Windows 11 operating system: 23H2

May you help me out with this issue please?

Thank you for for your time and help, it is greatly appreciated.

**Comment by xlatb** [comment]
It looks like this could be caused by the request to `https://accounts.nintendo.com/connect/1.0.0/api/session_token` failing.

I'm not sure why it would fail in your case. Are you able to use the same Nintendo account with the NSO app on iOS/Android?

Something you might do is try again with the debug level set to 3:
```
set NSO_API_DEBUG=3
nso-cli.py --login
```

This will print out the HTTP traffic. There might be a more illuminating error message in the HTTP response.

**Comment by Dyr-Fenrir** [comment]
Greetings,

I use the NSO app on Android every day for ACNH, I did try what you just asked (set debug to 3) and I get the same output:
`Traceback (most recent call last):
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\nso-cli.py", line 7, in <module>
    from nso_api.nso_api import NSO_API
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\nso_api\nso_api.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Maybe I need to do something else for the debug to work?

**Comment by Dyr-Fenrir** [comment]
I manually modified the nso_api.py to set the debug level to 3 and here is what I get:
`<PreparedRequest [POST]>
POST https://accounts.nintendo.com/connect/1.0.0/api/session_token
User-Agent: OnlineLounge/2.7.1 NASDKAPI Android
Accept-Encoding: gzip
Accept: application/json
Connection: Keep-Alive
Accept-Language: en-US
Content-Type: application/x-www-form-urlencoded
Host: accounts.nintendo.com
Content-Length: 503

client_id=CENSORED&session_token_code=CENSORED&session_token_code_verifier=CENSORED
<Response [400]>
400 Bad Request
Content-Type: application/json; charset=utf-8
Content-Length: 92
Server: nginx
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=2592000; includeSubDomains
Expires: Thu, 16 Nov 2023 21:31:04 GMT
Pragma: no-cache
Date: Thu, 16 Nov 2023 21:31:04 GMT
Connection: close
Cache-Control: private, no-cache, must-revalidate, no-store
Set-Cookie: _abck=CENSORED; Domain=.nintendo.com; Path=/; Expires=Fri, 15 Nov 2024 21:31:04 GMT; Max-Age=31536000; Secure, bm_sz=CENSORED; Domain=.nintendo.com; Path=/; Expires=Fri, 17 Nov 2023 01:31:04 GMT; Max-Age=14400

{"error_description":"The provided session_token_code is invalid","error":"invalid_request"}
Traceback (most recent call last):
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\nso-cli.py", line 281, in <module>
    if nso.complete_login_challenge(input):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\nso_api\nso_api.py", line 506, in complete_login_challenge
    if not result.get('session_token'):
           ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by Jetsurf** [comment]
Just verified this issue is popping up on Windows, but not on Linux. Need to explore what's going on a bit more

**Comment by Jetsurf** [comment]
Andy and I found out that links being put into the script on Windows was being truncated. Can you either `git pull` the latest version and install, or do a `pip install -U nso-api` and give it another shot?

**Comment by Dyr-Fenrir** [comment]
Amazing! I am getting `Login OK`! Thank you! Everything seems fine now.

Quick reply and quick fix, keep up the good work, it is greatly appreciated!
