### ISSUE TITLE
Errors while trying to run example.py

### ISSUE THREAD

**Issue by Dyr-Fenrir** [Jetsurf/nso-api#4]
Greetings again,

Since I was able to login successfully yesterday, with your help (which I am still grateful for!), the next logical step was to try to run example.py to see how the API was working.

I was getting an error though:
```
Traceback (most recent call last):
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\example.py", line 39, in <module>
    nso.on_keys_update(handle_keys_update)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NSO_API' object has no attribute 'on_keys_update'
```

So I looked in nso_api.py and I could not find `on_keys_update` so I commented it out to see if the rest of the code would go through and I got another error:
```
Traceback (most recent call last):
  File "G:\Program Files\Python\Nintendo Switch Online\nso-api\example.py", line 43, in <module>
    nso.set_global_data(load_json_file("nso_global_data.json"))
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NSO_API' object has no attribute 'set_global_data'. Did you mean: 'get_global_data'?
```

Then I stopped there, I thought, that maybe the API was updated along the way but not the example.

May you help me out with this again please?

Thank you for your time and help, it is greatly appreciated!

**Comment by xlatb** [comment]
It turns out example.py was not updated after some API calls were renamed.

Try this version and see how it goes: https://raw.githubusercontent.com/Jetsurf/nso-api/10df57c7c1c6fe12982fd672580041f91902345e/example.py

**Comment by Dyr-Fenrir** [comment]
All good now! Thank you a lot again! Really appreciated! Again, really fast answer and fix!
