### ISSUE TITLE
ACNH - Question regarding catalog retrieval

### ISSUE THREAD

**Issue by Dyr-Fenrir** [Jetsurf/nso-api#5]
Greetings,

I am currently exploring the API and my main goal would be to be able to retrieve the complete catalog from the NSO app to validate which items I am missing by comparing it with a complete catalog (several resources already exist online for a complete one, for example [https://mpql.net/tools/acnh/codes/item-list/](https://mpql.net/tools/acnh/codes/item-list/)).

So far, I was able to find some information here:
[https://github.com/ZekeSnider/NintendoSwitchRESTAPI/issues/13](https://github.com/ZekeSnider/NintendoSwitchRESTAPI/issues/13)

Particularly an answer to an issue regarding ACNH API stating the following endpoints:

> With the new catalog feature, we can access the user's catalog with the following endpoints:
> GET /api/sd/v1/catalog_items?language=ja-JP
> GET /api/sd/v1/catalog_items/latest
> GET, PUT, DELETE /api/sd/v1/catalog_items/favorites

I was able to add the following to `nso_api_acnh.py`:
```
	def get_catalog_items_latest_json(self):
		return self.get_authed_json("https://web.sd.lp1.acbaa.srv.nintendo.net/api/sd/v1/catalog_items/latest")

	def get_catalog_items_favorites_json(self):
		return self.get_authed_json("https://web.sd.lp1.acbaa.srv.nintendo.net/api/sd/v1/catalog_items/favorites")
```
Which are actually working and returning me the items.

Although, when I try the following endpoint:
```
	def get_catalog_items_json(self):
		return self.get_authed_json("https://web.sd.lp1.acbaa.srv.nintendo.net/api/sd/v1/catalog_items?language=en-US")
```
And do a print of the variable I am using `print(items)` I always get `None` as the output.

I am sure I am missing something, maybe I need to pass the ID of the item I need details on (easily fixed with a loop going through all items) or maybe the `GET` request is incomplete.

May you help me out with this please? I am aware that this is not a bug and more a question but this would really make things easier for me.

Thank you for your time and help, it is greatly appreciated again!

**Comment by xlatb** [comment]
The return value of None just means something went wrong. If you're able to set the debug level to 3 like before, that might help figure out what's going on.

**Comment by Jetsurf** [comment]
I'll be able to take a look at this after the holiday.

Just to add, the catalog being broken isn't very surprising as it wasn't originally a focus for this library. That said, it likely won't be too difficult to get working now that someone is actually looking to use nso-api to access it!

**Comment by Dyr-Fenrir** [comment]
Greetings,

> The return value of None just means something went wrong. If you're able to set the debug level to 3 like before, that might help figure out what's going on.

Sorry about that, here it is:

```
<PreparedRequest [GET]>
GET https://web.sd.lp1.acbaa.srv.nintendo.net/api/sd/v1/catalog_items?language=en-US
User-Agent: Mozilla/5.0 (Linux; Android 7.1.2; Pixel Build/NJH47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept: */*
Connection: keep-alive
Host: web.sd.lp1.acbaa.srv.nintendo.net
Referer: https://web.sd.lp1.acbaa.srv.nintendo.net/players/passport
Authorization: Bearer [CENSORED]
Accept-Language: en-us
Cookie: _park_session=[CENSORED]_park_session=[CENSORED]; _dnt=1

None
<Response [400]>
400 Bad Request
Content-Type: application/json
Content-Length: 20
Connection: keep-alive
Date: Thu, 23 Nov 2023 15:09:53 GMT
Server: nginx
Cache-Control: no-cache, no-store
Set-Cookie: _park_session=[CENSORED]; path=/; HttpOnly; SameSite=Lax
X-Request-Id: e71e3718a60217e5f2566726b33be0cf
X-Runtime: 0.033184
Vary: Origin
X-Cache: Error from cloudfront
Via: 1.1 7d7c52d1848969f2077d9502aa06f40e.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: YUL62-P2
X-Amz-Cf-Id: GuieBZDbfTHnFootyglz8i-3SKV3pQV0eGQ-kjsmY8Iuu0PPhQSC5A==

{
  "code": "3001"
}
None
```

> I'll be able to take a look at this after the holiday.
> 
> Just to add, the catalog being broken isn't very surprising as it wasn't originally a focus for this library. That said, it likely won't be too difficult to get working fully* now that someone is actually looking to use nso-api to access it!

I understand completely! Take your time! It is, again, greatly appreciated!

**Comment by xlatb** [comment]
I don't have ACNH so I can't test it personally, but I looked at the web app Javascript code from here: https://web.sd.lp1.acbaa.srv.nintendo.net/static/js/main.f259e2ce.chunk.js

This seems to be the code that builds the URL for the request:
`return i="/api/sd/v1/catalog_items?language=".concat(a,"&current_year=").concat(n)`

It looks to me like you don't just want:
`catalog_items?language=en-US` 
...but:
`catalog_items?language=en-US&current_year=x`.

I'm not sure what kind of value you'd need to provide for `current_year`, though.

**Comment by Jetsurf** [comment]
The actual API call is this:

`GET https://web.sd.lp1.acbaa.srv.nintendo.net/api/sd/v1/catalog_items?language=en-US&current_year=2023 HTTP/1.1`

Looks like it's just the year, and providing 2022 does return a result, but there doesn't seem to be any differences in the result.

**Comment by Dyr-Fenrir** [comment]
Greetings,

With the information you just provided, I was able to add this to `nso_api_acnh.py`:
```
	def get_catalog_items_json(self):
		return self.get_authed_json("https://web.sd.lp1.acbaa.srv.nintendo.net/api/sd/v1/catalog_items?language=en-US&current_year=2023")
```

And then do the following using a file which is an almost exact copy of `example.py` without the `ranks = nso.s2.get_ranks()` at the end, I replaced the 5 last lines with:
```
items = nso.acnh.get_catalog_items_json()
print(items)
```

I can now see my entire catalog! This is insane! Amazing! Thank you a lot again! I might now need to export the results and parse it correctly as there is too much data and the Windows Terminal cannot display all of it!

All the help is really appreciated! I will make sure to add another comment as soon as I am able with my progress.

**Comment by Dyr-Fenrir** [comment]
Greetings,

Just posting an update, according to the following: [https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file](https://stackoverflow.com/questions/12309269/how-do-i-write-json-data-to-a-file)

I changed my `example.py` by adding this in the `import` section:
`import json, codecs` (added `codecs`)

And added a write to a TXT file after the `print()`:
```
items = nso.acnh.get_catalog_items_json()
print(items)
with open('data.txt', 'wb') as f:
	json.dump(items, codecs.getwriter('utf-8')(f), ensure_ascii=False, indent=4)
```

I now have, in the PY file directory, a neatly indented output file named `data.txt` containing all the requested catalog items.

**Comment by xlatb** [comment]
Congrats on getting your code working. :-) Let us know if you run into any more issues with the library.

**Comment by Jetsurf** [comment]
The functions you added in your copy have been added into the library proper. Just note that the function names don't have the _json portion of their name in it. Thanks for taking a look at it!
