### ISSUE TITLE
I seem to be getting invalid tokens for ACNH

### ISSUE THREAD

**Issue by Dyr-Fenrir** [Jetsurf/nso-api#7]
Greetings,

I was updating my catalog this morning since it has been a few weeks and I am getting the following:

```
<PreparedRequest [POST]>
POST https://api-lp1.znc.srv.nintendo.net/v3/Account/Login
User-Agent: com.nintendo.znca/2.9.0 (Android/7.1.2)
Accept-Encoding: gzip
Accept: application/json
Connection: Keep-Alive
Host: api-lp1.znc.srv.nintendo.net
Accept-Language: en-US
X-ProductVersion: 2.9.0
Content-Type: application/json; charset=utf-8
Authorization: Bearer
X-Platform: Android
Content-Length: 1154

b'{"parameter": {"f": "<REDACTED>", "naIdToken": "<REDACTED>", "timestamp": 1708701396578, "requestId": "<REDACTED>", "naCountry": "CA", "naBirthday": "<REDACTED>", "language": "en-US"}}'
<Response [200]>
200 OK
Date: Fri, 23 Feb 2024 15:16:37 GMT
Content-Type: application/json
Vary: Accept-Encoding, Origin
Server: gunicorn
Allow: POST, OPTIONS
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Content-Encoding: gzip
Via: 1.1 google
Transfer-Encoding: chunked

{"status": 9403, "errorMessage": "Invalid token.", "correlationId": "414376b7-899d93c2"}
None
```

Login seems to be going through just fine:

```
Login challenge URL: <REDACTED>
Paste login URL here:
<REDACTED>
<PreparedRequest [POST]>
POST https://accounts.nintendo.com/connect/1.0.0/api/session_token
User-Agent: OnlineLounge/2.9.0 NASDKAPI Android
Accept-Encoding: gzip
Accept: application/json
Connection: Keep-Alive
Accept-Language: en-US
Content-Type: application/x-www-form-urlencoded
Host: accounts.nintendo.com
Content-Length: 534

client_id=<REDACTED>&session_token_code=<REDACTED>&session_token_code_verifier=<REDACTED>
<Response [200]>
200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 647
Server: nginx
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=2592000; includeSubDomains
Expires: Fri, 23 Feb 2024 15:16:16 GMT
Pragma: no-cache
Date: Fri, 23 Feb 2024 15:16:16 GMT
Connection: keep-alive
Cache-Control: private, no-cache, must-revalidate, no-store
Set-Cookie: _abck=<REDACTED>; Domain=.nintendo.com; Path=/; Expires=Sat, 22 Feb 2025 15:16:16 GMT; Max-Age=31536000; Secure, bm_sz=<REDACTED>; Domain=.nintendo.com; Path=/; Expires=Fri, 23 Feb 2024 19:16:16 GMT; Max-Age=14400

{"code":"<REDACTED>","session_token":"<REDACTED>"}
Login OK
```

Is it possible that some changes/updates were done on Nintendo's side and it is causing this please?

Thank you for your time and help again, as always, greatly appreciated!

**Comment by Jetsurf** [comment]
Hey!

Sorry for the bit of a slow response. Looks like 2.9.0 changed the f-token generation again. iMink hasn't been updated yet to support 2.9.0. Not sure at this time when it will be updated.

**Comment by xlatb** [comment]
As a temporary workaround, you can try forcing the previous version number.

For nso-cli.py, add the --override-app-version switch. Example: `./nso-cli.py --override-app-version 2.8.1 s3 get-splatfest-list`

In your own code, you can use the override_app_version() method. Example: `nso.override_app_version("2.8.1")`

**Comment by Dyr-Fenrir** [comment]
Greetings again,

I did some testing and apparently doing the override works for now, I will keep you both updated (sorry for the delay, I was not home in the past few days).

Thank you again for your time and help, as always, greatly appreciated!

**Comment by xlatb** [comment]
The newest code should work without any version number workaround needed. That's probably the better way to go since Nintendo could shut off support for the workaround version whenever they like.

**Comment by Dyr-Fenrir** [comment]
Greetings,

I just received an e-mail saying that this issue was closed, sorry you had to do it yourself, I forgot to update when I tried it again, it was working fine with the fallback solution and with the new update as well.

Thank you again for all the help and support, I apologize for the delay before replying, my mistake!
